version: '3'

services:
  nginx:
    container_name: popcat-wetherapp
    image: popcat-wetherapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10207:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
    restart: always
